apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: python:3
        command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:3000", "run:app"]
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "database-service"
        - name: DB_PORT
          value: "3306"
