stages:
  - test
  - build
  - push

variables:
  CONTAINER_REGISTRY:
  IMAGE_VARIANT: "production"

unit_test_app:
  stage: test
  script:
    - echo "Running unit tests for the app"
    - # TODO

feature_test_app:
  stage: test
  script:
    - echo "Running feature tests for the app"
    - # TODO

build_app:
  stage: build
  dependencies:
    - unit_test_app
    - feature_test_app
  script:
    - podman build -t $CONTAINER_REGISTRY/app:$IMAGE_VARIANT-$CI_COMMIT_SHA -f app/Containerfile .

push_app:
  stage: push
  dependencies:
    - build_app
  script:
    - podman push $CONTAINER_REGISTRY/app:$IMAGE_VARIANT-$CI_COMMIT_SHA
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then podman tag $CONTAINER_REGISTRY/app:$IMAGE_VARIANT-$CI_COMMIT_SHA $CONTAINER_REGISTRY/app:$IMAGE_VARIANT-latest && podman push $CONTAINER_REGISTRY/app:$IMAGE_VARIANT-latest; fi
