version: '3'
services:
  app:
    container_name: app
    #
    #image: 
    # or
    build:
      context: ./app/
      dockerfile: Containerfile
      args:
        image_variant: development
    #
    restart: "no"
    environment:
      APPLICATION_ENVIRONMENT: DEVELOPMENT
      APPLICATION_HOST: '0.0.0.0'
      APPLICATION_PORT: 80
    volumes:
      # Source code volume for live development from the host
      - ./src/:/usr/src/app/:Z
    ports:
      - 80:80
    links:
      - database
  
  database:
    container_name: database
    #
    #image: 
    # or
    image: mariadb:lts
    #
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: movie_app
      MYSQL_PASSWORD: movie_app1234
      MYSQL_DATABASE: movie_manager
    volumes:
      # Database conf files
      - ./conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:Z
      
      # Sql files to initialize the server with
      #
      # Note: Only scripts in that top-level directory
      #       are executed, in alphabetical order
      #
      - ./initdb/:/docker-entrypoint-initdb.d/:Z
      
      # Volume-out database data to host as a persistent, named volume
      - dbdata:/var/lib/mysql/:Z
    ports:
      - 3306:3306

volumes:
  dbdata:
