version: '3'
services:
  app:
    container_name: app
    restart: "no"
    working_dir: /var/www/html/
    build:
      context: ./app/
      dockerfile: ./containerfile
    args:
      image_variant: development
    environment:
      APPLICATION_ENVIRONMENT: DEVELOPMENT
      APPLICATION_HOST: '0.0.0.0'
      APPLICATION_PORT: 80
    volumes:
      # Source code volume for live development from the host
      - ./src/:/usr/src/app/:Z
    ports:
      - 80:80
    links:
      - database
  
  database:
    container_name: database
    restart: "no"
    build:
      context: ./database/
      dockerfile: ./containerfile
    args:
      image_variant: development
    environment:
      MYSQL_USER: movie_app
      MYSQL_PASSWORD: movie_app1234
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: movie_manager
    volumes:
      # Database conf files
      - ./conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:Z
      # Sql files to initialize the server with
      - ./initdb/:/docker-entrypoint-initdb.d/:Z
      # Additional sql files
      - ./sql/:/usr/src/sql/:Z
      # Persist database data to host
      - ./dbdata/:/var/lib/mysql/:Z
    ports:
      - 3306:3306
