version: '3'

services:
  api:
    container_name: api
    depends_on:
      - database
    #
    #image: # TODO: Pull and manage this image from our private container registry
    # or
    build:
      context: ./api/
      dockerfile: Containerfile
      args:
        image_variant: development
    #
    restart: "no"
    #
    # Uncomment to override the service container's
    # default command and entrypoint for debugging
    #command: ""
    #entrypoint: /bin/bash # podman run -i
    #tty: true             # podman run -t
    #
    env_file: ./env/api.env
    environment: # Override default dev env_file envvars here
      APPLICATION_ENABLE_DEBUGGER: true
      # On app startup, wait for the client to connect
      # to the debuggable app before starting execution
      APPLICATION_DEBUGGER_WAIT_FOR_CLIENT: false
      
      # Set this envvar to true to create the database table schemas
      #
      # Note: Unless you're intending to recrate the database,
      #       this envvar should only need to be set true the
      #       first time the database service is started,
      #       without any existing databases.
      #
      #       After that first run, the appropriate database
      #       table schemas will exist, and the dbdata volume
      #       will persist database files on disk between runs
      #
      APPLICATION_INIT_DATABASE: false
      
      APPLICATION_OMDBAPI_KEY: YOUR_KEY_HERE
    volumes:
      # Source code volume for live development from the host
      #
      # Note: You may comment out this volume to use the src/
      #       code that comes pre-built with this image variant
      - api-src:/usr/src/app/:Z
    ports:
      - 1234:5678 # For debugging
  
  api-reverse-proxy:
    container_name: api-reverse-proxy
    depends_on:
      - api
    image: nginx:stable # TODO: Pull and manage this image from our private container registry
    restart: "no"
    #
    # Uncomment to override the service container's
    # default command and entrypoint for debugging
    #command: ""
    #entrypoint: /bin/bash # podman run -i
    #tty: true             # podman run -t
    #
    env_file: ./env/api-reverse-proxy.env
    #environment: # Override default dev env_file envvars here
    #  OVERRIDE_ENVVARS_HERE=sample
    volumes:
      # App source volume for proxy to serve files from
      - api-src:/usr/src/app/:Z
      
      # Nginx conf files
      - ./api/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:Z
      
      # Nginx Logs
      - ./api/logs/reverse-proxy/:/var/log/nginx/:Z
  
  app:
    container_name: app
    depends_on:
      - api
    #
    #image: # TODO: Pull and manage this image from our private container registry
    # or
    build:
      context: ./app/
      dockerfile: Containerfile
      args:
        image_variant: development
    #
    restart: "no"
    #
    # Uncomment to override the service container's
    # default command and entrypoint for debugging
    #command: ""
    #entrypoint: /bin/bash # podman run -i
    #tty: true             # podman run -t
    #
    env_file: ./env/app.env
    environment: # Override default dev env_file envvars here
      APPLICATION_ENABLE_DEBUGGER: true
      # On app startup, wait for the client to connect
      # to the debuggable app before starting execution
      APPLICATION_DEBUGGER_WAIT_FOR_CLIENT: false
    volumes:
      # Source code volume for live development from the host
      #
      # Note: You may comment out this volume to use the src/
      #       code that comes pre-built with this image variant
      - app-src:/usr/src/app/:Z
    ports:
      - 8080:5678 # For debugging
  
  app-reverse-proxy:
    container_name: app-reverse-proxy
    depends_on:
      - app
    image: nginx:stable # TODO: Pull and manage this image from our private container registry
    restart: "no"
    #
    # Uncomment to override the service container's
    # default command and entrypoint for debugging
    #command: ""
    #entrypoint: /bin/bash # podman run -i
    #tty: true             # podman run -t
    #
    env_file: ./env/app-reverse-proxy.env
    #environment: # Override default dev env_file envvars here
    #  OVERRIDE_ENVVARS_HERE=sample
    volumes:
      # App source volume for proxy to serve files from
      - app-src:/usr/src/app/:Z
      
      # Nginx conf files
      - ./app/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:Z
      
      # Nginx Logs
      - ./app/logs/reverse-proxy/:/var/log/nginx/:Z

  database:
    container_name: database
    image: mariadb:lts # TODO: Pull and manage this image from our private container registry
    restart: "no"
    #
    # Uncomment to override the service container's
    # default command and entrypoint for debugging
    #command: ""
    #entrypoint: /bin/bash # podman run -i
    #tty: true             # podman run -t
    #
    env_file: ./env/database.env
    #environment: # Override default dev env_file envvars here
    #  OVERRIDE_ENVVARS_HERE=sample
    volumes:
      # Database conf files
      - ./database/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:Z
      
      # Sql files to initialize the server with
      #
      # Note: Only scripts in that top-level directory
      #       are executed, in alphabetical order
      #
      - ./database/initdb/:/docker-entrypoint-initdb.d/:Z
      
      # Volume-out database data to the host
      - ./database/dbdata:/var/lib/mysql/:Z
    ports:
      - 3306:3306
  
  gateway-reverse-proxy:
    container_name: gateway-reverse-proxy
    depends_on:
      - api-reverse-proxy
      - app-reverse-proxy
    image: nginx:stable # TODO: Pull and manage this image from our private container registry
    restart: "no"
    #
    # Uncomment to override the service container's
    # default command and entrypoint for debugging
    #command: ""
    #entrypoint: /bin/bash # podman run -i
    #tty: true             # podman run -t
    #
    env_file: ./env/gateway-reverse-proxy.env
    #environment: # Override default dev env_file envvars here
    #  OVERRIDE_ENVVARS_HERE=sample
    volumes:
      # Nginx conf files
      - ./gateway-reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:Z
      
      # Nginx Logs
      - ./gateway-reverse-proxy/logs/:/var/log/nginx/:Z
    ports:
      - 80:80     # App http server
      - 4321:4321 # Api http server

volumes:
  api-src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./api/src/
  app-src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./app/src/
