apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: python:3
        command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "run:app"]
        ports:
        - containerPort: 5000
