FROM python:3 AS base-image
    
    ARG image_variant
    ENV BUILD_ENVIRONMENT=${image_variant}

FROM base-image AS shared-base
    
    

FROM shared-base AS shared-os-dependencies
    
    # Install micropipenv
    pip install 'micropipenv>=1.8.0,<1.9.0'

FROM shared-base AS production-os-dependencies
    
    # Production-only os-level dependencies go here, for example

FROM shared-base AS development-os-dependencies
    
    # Development-only os-level dependencies go here, for example

FROM ${build_environment}-os-dependencies AS shared-project-dependencies
    
    # Shared project-level dependencies go here, for example
    
    WORKDIR /usr/src/app/
    # COPY in the Pipenv requirements independently of the app source
    COPY ./src/Pipfile ./

FROM shared-project-dependencies AS production-project-dependencies
    
    # Production-only project-level dependencies go here, for example
    
    RUN micropipenv install --method pipenv
    
FROM shared-project-dependencies AS development-project-dependencies
    
    # Development-only project-level dependencies go here, for example
    
    # Install app dependencies
    COPY ./src/Pipfile ./
    RUN micropipenv install --dev --method pipenv
    
    COPY ./src/ ./
