FROM python:3.12 AS base-image
    
    ARG image_variant
    ENV BUILD_ENVIRONMENT=${image_variant}

FROM base-image AS shared-base
    
    

FROM shared-base AS shared-os-dependencies
    
    # Install micropipenv
    pip install 'micropipenv>=1.8.0,<1.9.0'

FROM shared-base AS production-os-dependencies
    
    

FROM shared-base AS development-os-dependencies
    
    

FROM ${build_environment}-os-dependencies AS shared-project-dependencies
    
    WORKDIR /usr/src/app/
    
    # COPY in the Pipenv requirements independently of the app source
    COPY ./src/Pipfile ./

FROM shared-project-dependencies AS production-project-dependencies
    
    # Install prod app dependencies
    RUN micropipenv install --method pipenv
    
FROM shared-project-dependencies AS development-project-dependencies
    
    # Install app dependencies, including dev ones
    RUN micropipenv install --dev --method pipenv
    
    COPY ./src/ ./
