apiVersion: v1
kind: ConfigMap
metadata:
  name: reverse-proxy-config
data:
  reverse-proxy.conf: |
    events { }
    
    http {
        upstream api {
            server api-service:80;
        }
        
        server {
            listen 80;
            location / {
                proxy_pass http://api;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
