apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: common-config
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: app-code
          mountPath: /usr/src/app/
      volumes:
      - name: app-code
        persistentVolumeClaim:
          claimName: app-code-pvc
