name: Push Api Image

on:
  workflow_dispatch:
    inputs:
      service_name:
        type: string
        description: The name of this service
        required: true
        default: api
      container_name:
        type: string
        description: The name of the container being built and pushed
        required: true
        default: ${service_name}
      containerfile_path:
        type: string
        description: The path to the Containerfile
        required: true
        default: ${service_name}/Containerfile
      image_variant:
        type: choice
        description: The target image variant to build and push
        required: true
        options:
          - testing
          - development
          - staging
          - production

jobs:
  input_validation:
    uses: ./.github/workflows/shared.yml
    with:
      run_input_validation: true
      image_variant: ${image_variant}
    secrets: inherit
  
  functional_tests:
    runs-on: ubuntu-latest
    needs: [input_validation]
    steps:
      - name: Run the ${service_name} functional tests
        run: echo "Running the ${service_name} functional tests"
        # TODO: Checkout repo and run pytest on ${service_name}/tests/feature/*
  
  unit_tests:
    runs-on: ubuntu-latest
    needs: [functional_tests]
    steps:
      - name: Run the ${service_name} unit tests
        run: echo "Running the ${service_name} unit tests"
        # TODO: Checkout repo and run pytest on ${service_name}/tests/unit/*
  
  authenticate_container_registry:
    uses: ./.github/workflows/shared.yml
    with:
      run_authenticate_container_registry: true
    secrets: inherit
    
  build_container:
    uses: ./.github/workflows/shared.yml
    needs: [unit_tests, authenticate_container_registry]
    with:
      container_name: ${container_name}
      image_variant: ${image_variant}
      run_build_conainer: true
    secrets: inherit
  
  push_container:
    uses: ./.github/workflows/shared.yml
    needs: [build_container]
    with:
      container_name: ${container_name}
      image_variant: ${image_variant}
      run_push_conainer: true
    secrets: inherit
