name: api

on:
  workflow_dispatch:
    inputs:
      image_variant:
        type: choice
        description: Select the image variant to build
        required: true
        options:
          - testing
          - development
          - staging
          - production
      containerfile_path:
        type: string
        description: The path to the service Containerfile
        required: true
        default: api/Containerfile

jobs:
  input_validation:
    uses: ./.github/workflows/shared.yml#input-validation
  
  api_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run API unit tests
        run: echo "Running API unit tests"
  
  api_feature_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run API feature tests
        run: echo "Running API feature tests"
  
  api_build_container:
    uses: ./.github/workflows/shared.yml#build_container
    needs: [input_validation, api_unit_tests, api_feature_tests]
  
  api_push_container:
    uses: ./.github/workflows/shared.yml#push_container
    needs: build_container
