name: app

on:
  workflow_dispatch:
    inputs:
      image_variant:
        type: choice
        description: Select the image variant to build
        required: true
        options:
          - testing
          - development
          - staging
          - production
      containerfile_path:
        type: string
        description: The path to the service Containerfile
        required: true
        default: app/Containerfile

jobs:
  input_validation:
    uses: ./.github/workflows/shared.yml#input-validation
  
  app_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run app unit tests
        run: echo "Running app unit tests"
  
  app_feature_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run app feature tests
        run: echo "Running app feature tests"
  
  app_build_continaer:
    uses: ./.github/workflows/shared.yml#build_container
    needs: [input_validation, app_unit_tests, app_feature_tests]
  
  app_push_container:
    uses: ./.github/workflows/shared.yml#push_container
    needs: build
