name: app

stages:
  - tests
  - build
  - push

unit_tests:
  stage: tests
    script:
    - echo "Running unit tests"

feature_tests:
  stage: tests
  script:
    - echo "Running feature tests"

build_container:
  stage: build
  dependencies:
    - unit_tests
    - feature_tests
  script:
    - podman build -t registry.digitalocean.com/repo/app:$CI_COMMIT_SHA -f app/Containerfile .
    - podman tag registry.digitalocean.com/repo/app:$CI_COMMIT_SHA registry.digitalocean.com/repo/app:latest

push_container:
  stage: push
  dependencies:
    - build_container
  script:
    - podman push registry.digitalocean.com/repo/app:$CI_COMMIT_SHA
    - podman push registry.digitalocean.com/repo/app:latest

on:
  # https://github.com/orgs/community/discussions/48373#discussioncomment-8755119
  workflow_dispatch:
    inputs:
      image_variant:
        type: choice
        description: Select the image variant to build
        required: true
        options:
          - testing
          - development
          - staging
          - production
    jobs:
      input-validation:
        runs-on: ubuntu-latest
        steps:
          - name: Validate image_variant selection
            run: if [[ ! "${{ github.event.inputs.image_variant }}" =~ ^(testing|development|staging|production)$ ]]; then echo "Invalid image_variant! Possible values are 'testing', 'development', 'staging' or 'production'"; exit 1; fi
