name: Deploy an Environment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repo
        uses: actions/checkout@v4
      
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8.2
          github_token: ${{ secrets.CI_GITHUB_TOKEN }}
      
      - name: Initialize the OpenTofu stack
        run: tofu init
      
      - name: Validate the OpenTofu configuration
        run: tofu validate
      
      - name: Plan the OpenTofu deployment
        run: tofu plan
      
      - name: Apply the OpenTofu deployment
        run: tofu apply
        env:
          DO_TOKEN: ${{ secrets.DO_TOKEN }}
