name: Shared Workflows

jobs:
  # https://github.com/orgs/community/discussions/48373#discussioncomment-8755119
  input_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validate image_variant selection
        run: |
          if [[ ! "${{ github.event.inputs.image_variant }}" =~ ^(testing|development|staging|production)$ ]]; then
            echo "Invalid image_variant! Possible values are 'testing', 'development', 'staging' or 'production'"
            exit 1
          fi
  
  authenticate_container_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Login to the container registry
        run: doctl registry login
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  
  build_container:
    runs-on: ubuntu-latest
    needs: [input_validation, authenticate_container_registry]
    steps:
      - name: Checkout the git repo
        uses: actions/checkout@v4
      # https://stackoverflow.com/questions/59810838/how-to-get-the-short-sha-for-the-github-workflow
      - name: Build the ${{ inputs.container_name }} container
        run: |
          registry_url=${{ secrets.CONTAINER_REGISTRY_URL }}
          
          container_name=${{ inputs.container_name }}
          image_variant=${{ github.event.inputs.image_variant }}
          short_sha=$(git rev-parse --short HEAD)
          
          base_tag=$container_name:$image_variant
          
          sha_tag=$base_tag-$short_sha
          #branch_tag=$base_tag-$branch_name
          latest_tag=$base_tag-latest
          
          base_image_url=$registry_url/$base_tag:$image_variant
          
          sha_image_url=$base_image_url-$sha_tag
          branch_image_url=$base_image_url-$branch_tag
          latest_image_url=$base_image_url-$latest_tag
          
          podman build -t $sha_image_url -f ${{ github.event.inputs.containerfile_path }} .
          podman tag $sha_image_url $branch_image_url
          
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            podman tag $sha_image_url $latest_image_url
          fi
    inputs:
      container_name:
        description: 'The name of the container'
        required: true
        default: ${{ github.event.inputs.container_name }}
  
  push_container:
    runs-on: ubuntu-latest
    needs: [build_container, authenticate_container_registry]
    steps:
      - name: Checkout the git repo
        uses: actions/checkout@v4
      - name: Push the ${{ inputs.container_name }} container
        run: |
          podman push ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ inputs.container_name }}:${{ github.event.inputs.image_variant }}
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            podman push ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ inputs.container_name }}:latest
          fi
    inputs:
      container_name:
        description: 'The name of the container'
        required: true
        default: ${{ github.event.inputs.container_name }}
